### ISSUE TITLE
Tutorial document error

### ISSUE THREAD

**Issue by GregoryLi0** [Simple-XX/SimplePhysicsEngine#3]
Here are some errors in tutorial document
1. Link in the README can't be opened. https://github.com/Simple-XX/SimplePhysicsEngine#documentation (May be link to doc of dtk?)
2. Link below freeglut is not tutorial of freeglut. https://github.com/Simple-XX/SimplePhysicsEngine#freeglut

**Comment by xiaoerlaigeid** [comment]
Thanks. These have been fixed
