### ISSUE TITLE
Failed to build FemSimulation demo

### ISSUE THREAD

**Issue by GregoryLi0** [Simple-XX/SimplePhysicsEngine#5]
## Description
After successfuly build dtk of SimplePhysicsEngine, I tried to build and run FemSimulation. Errors occured while generating FemSimulation project.

## check steps done
1. install boost, CGAL, Eigen, GLM, freeglut.
2. generate, build and install dtk of SimplePhysicsEngine successfully.
3. change lib paths of `CMakeLists.txt` in `SimplePhysicsEngine\demo\FEMsimulation`.
4. use Cmake to config and generate VS project with config CGAL, Boost path.
5. while generating FemSimulation project, errors occured.

## Error code 
![image](https://user-images.githubusercontent.com/40971816/168540383-0edce18a-a9b9-4522-b6fa-d4cd995d8b58.png)
![Snipaste_2022-05-16_15-24-14](https://user-images.githubusercontent.com/40971816/168540343-b6276621-09f4-41ad-a1e4-54c39ca7791f.png)

It seems I failed to config dtk lib. But I have generated BUILD project of dtk, with `include` and `lib` folder generated in none-C-disk path. And I set correct dtk lib path of `CMakeLists.txt` in `SimplePhysicsEngine\demo\FEMsimulation`.

**Comment by TOMsworkspace** [comment]
The reason is the link error. You may link static lib with share lib or link share lib with static lib.

**Comment by MRNIU** [comment]
fixed #18
