### ISSUE TITLE
The total energy never stop increasing

### ISSUE THREAD

**Issue by VegetableDog-humble** [Simple-XX/SimplePhysicsEngine#8]
In the demo FEMSimulation, the total energy does not stop increasing thus goes incredibly high:
![image](https://user-images.githubusercontent.com/37610584/171613664-28bf651a-ca27-49ff-b928-be3d578e00f7.png)
Does this disobey the law of conservation of energy?

**Comment by MRNIU** [comment]
This example has been deprecated.
