### ISSUE TITLE
Object goes out of shape while increasing the Young's modulus

### ISSUE THREAD

**Issue by VegetableDog-humble** [Simple-XX/SimplePhysicsEngine#9]
When I increase the value of Young's modulus to 32000 while the Poisson Ratio is 0.3, the object goes out of shape:

![image](https://user-images.githubusercontent.com/37610584/171616287-6aa321ad-300f-4cad-af47-6838818f82fd.png)

But it is still normal when the Young's modulus is 31000. What special about this threshold and how can we deal with this kind of cases?

**Comment by MRNIU** [comment]
This example has been deprecated.
